/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package first;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        Student st=new Student();
        //ob.update(snew Student();
        st.setId(200);
        st.setName("test");

        StudImpl ob;

        ob=new StudImpl();
        ob.update(st);

    }
}
